//
//  File.swift
//  Dhanbarse
//
//  Created by Goldmedal on 12/12/19.
//  Copyright © 2019 Goldmedal. All rights reserved.
//

import Foundation
struct GlobalConstants {

    let CLIENT_ID = "DHA_625656"
    let CLIENT_SECRET = "8VapDMJlaor3v+EnezrePNSg+hMXt1OhvWIqX+7jIiIblilni65B4t0wkWXh8RVeBgOYtkrfT8SLAMkwziEMIlhuGuZfGvXdYoWpF6CpQ4c="
    let GRANT_TYPE_ACCESS = "password"
    let GRANT_TYPE_REFRESH = "refresh_token"
    let ORGANIZATION_ID = 1

//   Constant Variable for ID.
    let INTRO_ID = 1
    let SPLASH_ID = 2
    let CATEGORY_LOGIN_ID = 3
    let SEND_OTP_ID = 4
    let VERIFY_OTP_ID = 5
    let REGISTRATION_LOGIN_ID = 6
    let DASHBOARD_ID = 7
    let REGISTRATION_UPDATE_ID = 8
    let Passbook_ID = 9
    let POINTS_ID = 10
    let REWARD_STORE_ID = 11
    let REFERRAL_CODE_ID = 12
    let GAME_STORE_ID = 13
    let GIFT_STORE_ID = 14
    let SCHEME_ID = 15
    let WHATS_NEW_ID = 16
    let SOCIAL_ID = 17
    let NOTIFICATION_ID = 18
    let SCAN_QR_ID = 19
    let CHECK_QR_ID = 20
    let GIFT_HISTORY_ID = 21
    let REWARD_HISTORY_ID = 22
    let CHANGE_MOBILE_NO_ID = 23
    let ABOUT_US_ID = 24
    let CONTACT_US_ID = 25
    let PRIVACY_POLICY_ID = 26
    let COUNTER_BOY_ID = 27
    
    
    //   Constant Variable for Screen Name.
    let INTRO_SCREEN = "INTRO SCREEN"
    let SPLASH_SCREEN = "SPLASH SCREEN"
    let CATEGORY_LOGIN_SCREEN = "CATEGORY LOGIN SCREEN"
    let SEND_OTP_SCREEN = "RECEIVE OTP SCREEN"
    let VERIFY_OTP_SCREEN = "VERIFY OTP SCREEN"
    let REGISTRATION_LOGIN_SCREEN = "REGISTRATION SCREEN"
    let DASHBOARD_SCREEN = "DASHBOARD SCREEN"
    let REGISTRATION_UPDATE_SCREEN = "PROFILE UPDATE SCREEN"
    let Passbook_SCREEN = "Passbook SCREEN"
    let POINTS_SCREEN = "POINTS SCREEN"
    let REWARD_STORE_SCREEN = "REWARD STORE SCREEN"
    let REFERRAL_CODE_SCREEN = "REFERRAL CODE SCREEN"
    let GAME_STORE_SCREEN = "GAME STORE SCREEN"
    let GIFT_STORE_SCREEN = "GIFT STORE SCREEN"
    let SCHEME_SCREEN = "SCHEME SCREEN"
    let WHATS_NEW_SCREEN = "WHATS NEW SCREEN"
    let SOCIAL_SCREEN = "SOCIAL SCREEN"
    let NOTIFICATION_SCREEN = "NOTIFICATION SCREEN"
    let SCAN_QR_SCREEN = "SCAN QR SCREEN"
    let CHECK_QR_SCREEN = "CHECK QR SCREEN"
    let GIFT_HISTORY_SCREEN = "GIFT HISTORY SCREEN"
    let REWARD_HISTORY_SCREEN = "REWARD HISTORY SCREEN"
    let CHANGE_MOBILE_NO_SCREEN = "CHANGE MOBILE NO SCREEN"
    let ABOUT_US_SCREEN = "ABOUT US SCREEN"
    let CONTACT_US_SCREEN = "CONTACT US SCREEN"
    let PRIVACY_POLICY_SCREEN = "PRIVACY POLICY SCREEN"
    let COUNTER_BOY_SCREEN = "COUNTER BOY SCREEN"
}
