//
//  StringConstant.swift
//  Dummy
//
//  Created by Goldmedal on 16/09/21.
//

import Foundation
struct StringConstants {
    
    static let app_name = "FSLPro"
    static let home = "Home"
    static let dashboard_small = "DASHBOARD"
    static let str_profile = "PROFILE"
    static let str_premium = "PREMIUM"
    static let str_how_to_play = "HOW TO PLAY"
    static let str_point_system = "POINT SYSTEM"
    static let str_advertisement = "ADVERTISEMENT"
    static let str_about_us = "ABOUT US"
    static let navigation_drawer_open = "Open navigation drawer"
    static let navigation_drawer_close = "Close navigation drawer"
    static let str_ok = "Ok"
    static let str_dash = "-"
    static let str_logout = "Logout"
    static let press_back_again = "Please click BACK again to exit"
    static let str_new_update = "NEW UPDATE !"
    static let app_update_description_text = "There is a newer version available for download! Please update the app by visiting the Play Store."
    static let str_upcoming = "UPCOMING"
    static let str_live = "LIVE"
    static let str_completed = "COMPLETED"
    static let str_leagues = "LEAGUES"
    static let str_my_team = "MY TEAM"
    static let str_my_leagues = "MY LEAGUES"
    static let create_team = "CREATE TEAM"
    static let str_preview = "PREVIEW"
    static let str_edit = "EDIT"
    static let str_about_match = "ABOUT MATCH"
    static let timer_placeholder = "- : - : -"
    static let entry = "ENTRY"
    static let winners = "WINNERS"
    static let price = "PRICE"
    static let lowercase_price = "Price"
    static let distribution = "Distribution"
    static let rank = "Rank"
    static let str_view = "VIEW"
    static let str_refunded = "REFUNDED"
    static let str_country = "Country"
    static let players = "Players"
    static let str_leaderboard = "LEADERBOARD"
    static let str_live_score = "LIVE SCORE"
    static let str_scorecard = "SCORECARD"
    static let str_winning = "Winning"
    static let str_points = "Points"
    static let fsl_logo = "FSL Logo"
    static let str_next = "Next"
    static let str_save = "Save"
    static let str_zero = "0"
    static let str_login = "LOGIN"
    static let str_terms = "I agree to the <b>Terms and Conditions</b> &amp; <b>Privacy Policy.</b>"
    static let app_name_short = "AppAuth"
    static let auth_granted = "Authorization granted"
    static let intro_header = "OpenID AppAuth Demo"
    static let openid_logo_content_description = "AppAuth Logo"
    static let refresh_token = "Refresh token"
    static let access_token_expires_at = "Access token expires at: %s"
    static let no_access_token_returned = "No access token returned"
    static let no_refresh_token_returned = "No refresh token returned"
    static let refresh_token_returned = "Refresh token returned"
    static let no_id_token_returned = "No ID token returned"
    static let id_token_returned = "ID token returned"
    static let view_profile = "View user info"
    static let userinfo_profile_content_description = "User profile picture"
    static let login_hint_value = "Mobile No"
    static let hint_team_name = "Team Name"
    static let hint_first_name = "First Name"
    static let hint_last_name = "Last Name"
    static let hint_dob = "Date of birth"
    static let hint_gender = "Gender"
    static let hint_email = "Email"
    static let hint_mobile_no = "Mobile Number"
    static let account_id_description = "The Account ID is optional. If specified, it is transmitted as a login_hint parameter in the authorization request."
    static let auth_options = "Authorization options:"
    static let browser_selector_label = "Use browser:"
    static let browser_icon_contentDescription = "Browser app icon"
    static let browser_appauth_default_label = "AppAuth heuristic selection"
    static let retry_label = "Retry"
    static let not_authorized = "Not authorized"
    static let start_authorization = "Start authorization"
    static let reauthorize = "Reauthorize"
    static let sign_out = "Sign out"
    static let no_access_token_expiry = "Access time has no defined expiry"
    static let access_token_expired = "Access token has expired"
    static let auth_settings = "Authorization settings in use:"
    static let use_pending_intents = "Use PendingIntent\'s for completion"
    static let str_otp = "OTP"
    static let verification_code_subtext = "Please type the verification code sent to +xxxxxxxxxx"
    static let verification_code = "Verification Code"
    static let validate = "Validate"
    static let str_particular = "PARTICULAR"
    static let str_details = "DETAILS"
    static let str_toss = "Toss"
    static let str_match = "Match"
    static let str_time = "Time"
    static let str_venue = "Venue"
    static let str_series = "Series"
    static let str_date = "Date"
    static let str_umpire = "Umpire"
    static let str_3rd_umpire = "3rd Umpire"
    static let str_referee = "Referee"
    static let str_go_premium = "Go PREMIUM"
}
